version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Backend-Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_SYSTEM_PROMPT=${OPENAI_SYSTEM_PROMPT}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS}
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  frontend:
    build:
      context: .
      dockerfile: Frontend-Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0